// <auto-generated />
using System;
using ChatApp.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatApp.Data.Migrations
{
    [DbContext(typeof(ChatAppDbContext))]
    [Migration("20240104005842_newDatabaseWithSeedData")]
    partial class newDatabaseWithSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.Data.Entities.Models.GroupMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SenderUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupID");

                    b.HasIndex("SenderUserID");

                    b.ToTable("GroupMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupID = 1,
                            MessageText = "Hello everyone!",
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5864)
                        },
                        new
                        {
                            Id = 2,
                            GroupID = 1,
                            MessageText = "Yo yo whats up guys?",
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5905)
                        },
                        new
                        {
                            Id = 3,
                            GroupID = 1,
                            MessageText = "Merry Christmas everyone!",
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5908)
                        },
                        new
                        {
                            Id = 4,
                            GroupID = 1,
                            MessageText = "Happy ne year!",
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5911)
                        },
                        new
                        {
                            Id = 5,
                            GroupID = 1,
                            MessageText = "yoyoyo whatsup!",
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5915)
                        },
                        new
                        {
                            Id = 6,
                            GroupID = 1,
                            MessageText = "Good, what about you?",
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5918)
                        },
                        new
                        {
                            Id = 7,
                            GroupID = 1,
                            MessageText = "How is the project going?",
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5926)
                        },
                        new
                        {
                            Id = 8,
                            GroupID = 2,
                            MessageText = "How is the wheather?",
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5930)
                        },
                        new
                        {
                            Id = 9,
                            GroupID = 2,
                            MessageText = "Very good! its sunny.",
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5943)
                        },
                        new
                        {
                            Id = 10,
                            GroupID = 2,
                            MessageText = "Happy new year everyone!",
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5946)
                        },
                        new
                        {
                            Id = 11,
                            GroupID = 2,
                            MessageText = "yoyo whatsup, happy new year aswell!",
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5954)
                        },
                        new
                        {
                            Id = 12,
                            GroupID = 2,
                            MessageText = "all the best in the new year everyone!",
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5957)
                        },
                        new
                        {
                            Id = 13,
                            GroupID = 2,
                            MessageText = "Happy new year!",
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5960)
                        },
                        new
                        {
                            Id = 14,
                            GroupID = 2,
                            MessageText = "Hello, also wishing everyone the best",
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5963)
                        },
                        new
                        {
                            Id = 15,
                            GroupID = 3,
                            MessageText = "hey does anyone wanna hang out tonight?",
                            SenderUserID = 8,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5966)
                        },
                        new
                        {
                            Id = 16,
                            GroupID = 3,
                            MessageText = "Sure, im free tonight!",
                            SenderUserID = 9,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5987)
                        },
                        new
                        {
                            Id = 17,
                            GroupID = 3,
                            MessageText = "I cant, im busy tonight.",
                            SenderUserID = 10,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5991)
                        },
                        new
                        {
                            Id = 18,
                            GroupID = 3,
                            MessageText = "I can, but im really tired today.",
                            SenderUserID = 11,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5994)
                        },
                        new
                        {
                            Id = 19,
                            GroupID = 4,
                            MessageText = "yoyo whatsup everyone!",
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(5997)
                        },
                        new
                        {
                            Id = 20,
                            GroupID = 4,
                            MessageText = "good, what about you?",
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6000)
                        },
                        new
                        {
                            Id = 21,
                            GroupID = 4,
                            MessageText = "Im fine, just working a lot lately",
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6003)
                        },
                        new
                        {
                            Id = 22,
                            GroupID = 4,
                            MessageText = "Hello, im doing good",
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6006)
                        },
                        new
                        {
                            Id = 23,
                            GroupID = 5,
                            MessageText = "Where would you like to travel next guys?",
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6009)
                        },
                        new
                        {
                            Id = 24,
                            GroupID = 5,
                            MessageText = "I would like to go to Italy",
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6012)
                        },
                        new
                        {
                            Id = 25,
                            GroupID = 5,
                            MessageText = "I would like to go to Spain",
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6015)
                        },
                        new
                        {
                            Id = 26,
                            GroupID = 5,
                            MessageText = "I would like to go to France",
                            SenderUserID = 8,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6018)
                        },
                        new
                        {
                            Id = 27,
                            GroupID = 5,
                            MessageText = "I would also love to go to France",
                            SenderUserID = 9,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6022)
                        },
                        new
                        {
                            Id = 28,
                            GroupID = 5,
                            MessageText = "Me too!",
                            SenderUserID = 10,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6025)
                        },
                        new
                        {
                            Id = 29,
                            GroupID = 5,
                            MessageText = "Then France it is?",
                            SenderUserID = 11,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6078)
                        },
                        new
                        {
                            Id = 30,
                            GroupID = 1,
                            MessageText = "Helloooo!",
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6087)
                        },
                        new
                        {
                            Id = 31,
                            GroupID = 1,
                            MessageText = "Hello helooo!",
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6130)
                        },
                        new
                        {
                            Id = 32,
                            GroupID = 1,
                            MessageText = "Hello yoyooy!",
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6133)
                        },
                        new
                        {
                            Id = 33,
                            GroupID = 1,
                            MessageText = "Hello whats upp!",
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6137)
                        },
                        new
                        {
                            Id = 34,
                            GroupID = 1,
                            MessageText = "yoyoyo whatsup!",
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6140)
                        });
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.Groups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "DUMP"
                        },
                        new
                        {
                            Id = 2,
                            GroupName = "fesb"
                        },
                        new
                        {
                            Id = 3,
                            GroupName = "pmf"
                        },
                        new
                        {
                            Id = 4,
                            GroupName = "family"
                        },
                        new
                        {
                            Id = 5,
                            GroupName = "friends"
                        });
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.GroupUsers", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupUsers");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 4
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 5
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 6
                        },
                        new
                        {
                            GroupId = 1,
                            UserId = 7
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 1
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 2
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 3
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 4
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 5
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 6
                        },
                        new
                        {
                            GroupId = 2,
                            UserId = 7
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 8
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 9
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 10
                        },
                        new
                        {
                            GroupId = 3,
                            UserId = 11
                        },
                        new
                        {
                            GroupId = 4,
                            UserId = 4
                        },
                        new
                        {
                            GroupId = 4,
                            UserId = 5
                        },
                        new
                        {
                            GroupId = 4,
                            UserId = 6
                        },
                        new
                        {
                            GroupId = 4,
                            UserId = 7
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 5
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 6
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 7
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 8
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 9
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 10
                        },
                        new
                        {
                            GroupId = 5,
                            UserId = 11
                        });
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.PrivateMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReceiverUserID")
                        .HasColumnType("integer");

                    b.Property<int>("SenderUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverUserID");

                    b.HasIndex("SenderUserID");

                    b.ToTable("PrivateMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 2,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6169)
                        },
                        new
                        {
                            Id = 2,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 1,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6173)
                        },
                        new
                        {
                            Id = 3,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 2,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6176)
                        },
                        new
                        {
                            Id = 4,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 3,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6179)
                        },
                        new
                        {
                            Id = 5,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 1,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6182)
                        },
                        new
                        {
                            Id = 6,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 3,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6185)
                        },
                        new
                        {
                            Id = 7,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 4,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6188)
                        },
                        new
                        {
                            Id = 8,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 1,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6191)
                        },
                        new
                        {
                            Id = 9,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 4,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6194)
                        },
                        new
                        {
                            Id = 10,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 5,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6197)
                        },
                        new
                        {
                            Id = 11,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 1,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6200)
                        },
                        new
                        {
                            Id = 12,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 5,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6203)
                        },
                        new
                        {
                            Id = 13,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 6,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6206)
                        },
                        new
                        {
                            Id = 14,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 1,
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6209)
                        },
                        new
                        {
                            Id = 15,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 6,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6212)
                        },
                        new
                        {
                            Id = 16,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 7,
                            SenderUserID = 1,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6215)
                        },
                        new
                        {
                            Id = 17,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 1,
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6219)
                        },
                        new
                        {
                            Id = 18,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 7,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6222)
                        },
                        new
                        {
                            Id = 19,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 3,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6225)
                        },
                        new
                        {
                            Id = 20,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 2,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6228)
                        },
                        new
                        {
                            Id = 21,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 3,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6231)
                        },
                        new
                        {
                            Id = 22,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 4,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6234)
                        },
                        new
                        {
                            Id = 23,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 2,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6237)
                        },
                        new
                        {
                            Id = 24,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 4,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6239)
                        },
                        new
                        {
                            Id = 25,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 5,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6242)
                        },
                        new
                        {
                            Id = 26,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 2,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6245)
                        },
                        new
                        {
                            Id = 27,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 5,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6248)
                        },
                        new
                        {
                            Id = 28,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 6,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6251)
                        },
                        new
                        {
                            Id = 29,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 2,
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6254)
                        },
                        new
                        {
                            Id = 30,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 6,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6257)
                        },
                        new
                        {
                            Id = 31,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 7,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6260)
                        },
                        new
                        {
                            Id = 32,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 2,
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6263)
                        },
                        new
                        {
                            Id = 33,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 7,
                            SenderUserID = 2,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6266)
                        },
                        new
                        {
                            Id = 34,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 4,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6269)
                        },
                        new
                        {
                            Id = 35,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 3,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6272)
                        },
                        new
                        {
                            Id = 36,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 4,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6275)
                        },
                        new
                        {
                            Id = 37,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 5,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6278)
                        },
                        new
                        {
                            Id = 38,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 3,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6281)
                        },
                        new
                        {
                            Id = 39,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 5,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6284)
                        },
                        new
                        {
                            Id = 40,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 6,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6286)
                        },
                        new
                        {
                            Id = 41,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 3,
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6289)
                        },
                        new
                        {
                            Id = 42,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 6,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6292)
                        },
                        new
                        {
                            Id = 43,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 7,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6295)
                        },
                        new
                        {
                            Id = 44,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 3,
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6298)
                        },
                        new
                        {
                            Id = 45,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 7,
                            SenderUserID = 3,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6301)
                        },
                        new
                        {
                            Id = 46,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 5,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6304)
                        },
                        new
                        {
                            Id = 47,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 4,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6307)
                        },
                        new
                        {
                            Id = 48,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 5,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6310)
                        },
                        new
                        {
                            Id = 49,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 6,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6313)
                        },
                        new
                        {
                            Id = 50,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 4,
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6316)
                        },
                        new
                        {
                            Id = 51,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 6,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6319)
                        },
                        new
                        {
                            Id = 52,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 7,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6322)
                        },
                        new
                        {
                            Id = 53,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 4,
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6325)
                        },
                        new
                        {
                            Id = 54,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 7,
                            SenderUserID = 4,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6328)
                        },
                        new
                        {
                            Id = 55,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 6,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6331)
                        },
                        new
                        {
                            Id = 56,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 5,
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6334)
                        },
                        new
                        {
                            Id = 57,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 6,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6336)
                        },
                        new
                        {
                            Id = 58,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 7,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6339)
                        },
                        new
                        {
                            Id = 59,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 5,
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6343)
                        },
                        new
                        {
                            Id = 60,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 7,
                            SenderUserID = 5,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6345)
                        },
                        new
                        {
                            Id = 61,
                            MessageText = "Hello, how are you?",
                            ReceiverUserID = 7,
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6348)
                        },
                        new
                        {
                            Id = 62,
                            MessageText = "Im good, what about you?",
                            ReceiverUserID = 6,
                            SenderUserID = 7,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6351)
                        },
                        new
                        {
                            Id = 63,
                            MessageText = "Im good aswell, just working a lot lately",
                            ReceiverUserID = 7,
                            SenderUserID = 6,
                            SentDate = new DateTime(2024, 1, 4, 1, 58, 40, 919, DateTimeKind.Local).AddTicks(6354)
                        });
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLogged")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anteAdmin@gmail.com",
                            IsAdmin = true,
                            IsLogged = false,
                            Password = "123456",
                            UserName = "AnteAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tonigrbic@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "ToniGrbic"
                        },
                        new
                        {
                            Id = 3,
                            Email = "matematic@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "Matematic"
                        },
                        new
                        {
                            Id = 4,
                            Email = "anteantic1@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "AnteAntic1"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ivoIvic@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "IvoIvic"
                        },
                        new
                        {
                            Id = 6,
                            Email = "anaAnjic@gmail.com",
                            IsAdmin = true,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "AnaAnjic"
                        },
                        new
                        {
                            Id = 7,
                            Email = "ivaIvic23@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "IvaIvic23"
                        },
                        new
                        {
                            Id = 8,
                            Email = "mateaMatic2@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "MateaMatic2"
                        },
                        new
                        {
                            Id = 9,
                            Email = "simesimic@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "SimeSimic"
                        },
                        new
                        {
                            Id = 10,
                            Email = "antonioAntic12@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "AntonioAntic12"
                        },
                        new
                        {
                            Id = 11,
                            Email = "josipJosipovic@gmail.com",
                            IsAdmin = false,
                            IsLogged = false,
                            Password = "pass123",
                            UserName = "JosipJosipovic"
                        });
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.GroupMessages", b =>
                {
                    b.HasOne("ChatApp.Data.Entities.Models.Groups", "Group")
                        .WithMany("GroupMessages")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatApp.Data.Entities.Models.Users", "SenderUser")
                        .WithMany("GroupMessages")
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.GroupUsers", b =>
                {
                    b.HasOne("ChatApp.Data.Entities.Models.Groups", "Group")
                        .WithMany("GroupUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatApp.Data.Entities.Models.Users", "User")
                        .WithMany("GroupUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.PrivateMessages", b =>
                {
                    b.HasOne("ChatApp.Data.Entities.Models.Users", "ReceiverUser")
                        .WithMany("PrivateMessagesReceived")
                        .HasForeignKey("ReceiverUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatApp.Data.Entities.Models.Users", "SenderUser")
                        .WithMany("PrivateMessagesSent")
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.Groups", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("GroupUsers");
                });

            modelBuilder.Entity("ChatApp.Data.Entities.Models.Users", b =>
                {
                    b.Navigation("GroupMessages");

                    b.Navigation("GroupUsers");

                    b.Navigation("PrivateMessagesReceived");

                    b.Navigation("PrivateMessagesSent");
                });
#pragma warning restore 612, 618
        }
    }
}
